name: Install Directory and custom paths
                                                                                                                                                                                                                                         
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
                                                                                                                                                                                                                                         
jobs:
  blackduck-sca-scan:
    runs-on: [mac-arm-sh]
                                                                                                                                                                                                                                         
    steps:
    
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Create detect install directory                                                                                                                                                                                                  
      run: mkdir -p detect-install-directory                                                                                                                                                                                                 
      shell: bash                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                         
    - name: Black Duck SCA Scan with Custom paths
      uses: blackduck-inc/black-duck-security-scan@v2
      with:
        blackducksca_url: ${{ vars.BLACKDUCKSCA_URL }}
        blackducksca_token: ${{ secrets.BLACKDUCKSCA_TOKEN }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        detect_args: "--detect.source.path=${{ github.workspace }}/nodejs-npm"
        detect_install_directory: detect-install-directory

      env:
        DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
